version: '3'
services:
  toolbox:
    build: .
    image: idahodata/toolbox
    env_file: toolbox.env
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
